### ISSUE TITLE
Dialog boxes like "File Open" are very narrow and have no title in some (gtk2) apps like LibreOffice

### ISSUE THREAD

**Issue by Sadi58** [linuxmint/mint-themes#151] opened 2018-10-19 10:13 UTC
I see this problem in a few gtk2 apps as well as LibreOffice on the latest Linux Mint Cinnamon.

![selection_2018-10-19-13 05 34](https://user-images.githubusercontent.com/6375934/47212369-a3bb7680-d3a0-11e8-854c-7e5bd506f19d.jpg)

**Comment by JosephMcc** [comment] 2018-11-03 07:53
I can't reproduce this issue in LibreOffice 6.0.6.2 in Mint19 on the latest Mint-Y from git master.

**Comment by Sadi58** [comment] 2018-11-03 12:45
I tried the latest Mint-Y from git master, but saw no change in LibreOffice 6.0.6.2 in Mint19 (I only saw a larger cinnamon desktop panel).
This problem also affects other (gtk2?) apps like thunderbird (Save Message As...), medit (File Open/Save As), etc.
How I built and tested the Mint-Y theme from gitmaster:
1. cd to  ~/mint-themes-master
2. Enter command ./generate-themes.py
3. cd to ./mint-themes-master/usr/share/themes/
4. Rename folder Mint-Y to Mint-Y-git (also editing index.theme inside accordingly)
5. Copy folder Mint-Y-git to ~/.themes/
6. Select theme Mint-Y-git

**Comment by JosephMcc** [comment] 2018-12-22 07:50
I'm assuming you have the "Attach dialogs to the parent windows" setting turned on. That would explain why I didn't see it since it is off by default. This should have been fixed by: https://github.com/linuxmint/mint-themes/commit/23bc5cad49f56778e466759d5b6cb66a0f14cf89

**Closed by JosephMcc** 2018-12-22 07:50 UTC
