### ISSUE TITLE
Dark variant of Mint-Y themes break when setting org.gnome.desktop.inferface.color-scheme to "Prefer-Dark"

### ISSUE THREAD

**Issue by AchillesBoi** [linuxmint/mint-themes#420] opened 2023-01-03 16:48 UTC
When using the dark variant of Mint-Y themes, libadwaita apps remain in Light mode. To make libadwaita apps switch to Dark mode, one must change `org.gnome.desktop.inferface.color-scheme` to "Prefer-Dark". This in turn breaks Mint-Y themes but only the Dark variants; regular GTK3 apps will display in the old classic Adwaita theme instead of Mint-Y.

**Comment by JosephMcc** [comment] 2023-01-04 00:36
Mint themes doesn't currently support libadwaita.

**Comment by AchillesBoi** [comment] 2023-01-04 00:38
You don't understand. I'm not talking about themeing libadwaita, I'm talking about Mint-Themes letting libadwaita apps know that they're light or dark so that libadwaita apps can also switch from light to dark mode and vice versa. The old Mint-Themes used to do this, now it's been broken since Mint 21.0

**Comment by AchillesBoi** [comment] 2023-02-13 17:56
This seems to be a fairly easy-to-fix issue but strangely no discussion about it so far...

**Comment by Uldreth** [comment] 2023-05-28 21:11
Apparantly this issue is caused by GTK expecting dark variants to end in <theme name>-dark (with an uncapitalized "dark" even).

A quick workaround is to copy eg. /usr/share/themes/Mint-Y-Dark-Aqua to /usr/share/themes/Mint-Y-Aqua-dark and in the directory change the index.theme accordingly. Then this issue will be gone, but GTK3 flatpak applications will no longer recognize the theme, which can be worked around via [stylepak](https://github.com/refi64/stylepak).

The Mint themes should be renamed upstream so that all dark variants end in "-dark".

**Comment by mtwebster** [comment] 2023-05-29 01:26
The OP's issue will be addressed in Mint 21.2 by the new [xdg-desktop-portal-xapp](https://github.com/linuxmint/xdg-desktop-portal-xapp) package.

ref: https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Closed by mtwebster** 2023-05-29 01:26 UTC
