### ISSUE TITLE
Ran scripts and no theme in personalization in MATE

### ISSUE THREAD

**Issue by adrummer354** [linuxmint/mint-themes#228] opened 2019-09-01 15:30 UTC
I ran the scripts here on my Linux Mint 19.2 MATE machine as instructed with no apparent issues and I see no output for the theme with my custom name which I indicated in script 4.

**Comment by JosephMcc** [comment] 2019-09-01 19:10
You're going to have to clarify what you are talking about for me. I'm honestly a bit lost :)

**Comment by adrummer354** [comment] 2019-09-01 20:02
I went to go try to change the default icon theme color Linux Mint 19.2 MATE from green to a custom color #313C4E so that it would match a MATE theme I downloaded from Mate-look - The theme is called Materia Breeze GTK. If you use the scripts from https://github.com/HattDroid/Mint-Y-Colora-Theme apparently the scripts will create a new theme that you can name.  I tried using the provided scripts in the original post here: https://github.com/erikdubois/Mint-Y-Colora-Theme. I used the following process:

1. Went to the link here: https://github.com/HattDroid/Mint-Y-Colora-Theme which is the forked version of the original script provided from here: https://github.com/erikdubois/Mint-Y-Colora-Theme
2. Ran sudo apt-get install git
3. Ran git clone https://github.com/linuxmint/mint-y-theme
4. Ran git clone https://github.com/erikdubois/Mint-Y-Colora-Theme
5. Copied scripts from Mint-Y-Colora-Theme into mint-y-theme
6. Before running scripts opented the first script file 1-change-color.sh and updated it to my custom color number of #313C4E for light and dark
7. Ran script files 1-4 in order and they all completed. 
8. I went to appearance but no theme that I named is listed there.

**Comment by JosephMcc** [comment] 2019-09-01 20:08
Ok. Thank you for taking the time to explain what you were doing. But I'm going to close this since mint-themes builds and installs fine. The issue is with the other stuff you are using and you need to report it to them.

**Closed by JosephMcc** 2019-09-01 20:08 UTC
